export const FETCH_QUESTION = 'FETCH_QUESTION';
export const RECEIVE_QUESTION = 'RECEIVE_QUESTION';
export const QUESTION_ANSWERED = 'QUESTION_ANSWERED';
export const NEXT_QUESTION = 'NEXT_QUESTION';
export const GAME_FINISHED = 'GAME_FINISHED';